development:
  adapter: postgresql
  database: github_trending_users_dev
  host: localhost

test:
  adapter: postgresql
  database: github_trending_users_test
  host: localhost

# this is only for running locally production environment 
# as heroku automatically generates a new database.yml for postgres 
production: 
  uri: <%= ENV['HEROKU_POSTGRESQL_CYAN_URL'] %>
